Version 2
Abrar052/Microverse-Portfolio-Mobile-Version pull request #2
Opened 2022-07-02 19:45 UTC by Abrar052

###Microverse Portfolio Project (Mobile version)
-Updated index.html by Adding Next Two Sections
-Updated style.css by Adding Style to New Two Sections 
-Updated Json Packages
 -Updated .gitignore
 -Added Images to the New Sections

2022-07-02 21:10 UTC, prolajumokeoni requested changes
Hi @Abrar052, 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design 



## Required Changes ♻️

- [ ] Kindly make sure that git properly ignores node modules, currently, some files from node modules are still pushed to git, this may happen [if you had commited them in previous commit to git](https://gist.github.com/pavankjadda/2bb6fbdd8786e1f57fd7bcbcc666b51d). Please check fix this 🤝

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 21:10 UTC, prolajumokeoni commented on index.html
> +    <div class="grid-container">
- [ ] The container of the section is a section tag, please change the main wrapper of this section to a section tag, based on the requirements and for semantic purposes 👍🏿 
- [ ] Please align all content in this section to the center currently your cards are not aligned properly, see screen shot below 👍🏿  


Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Template 2-Main-Mobile](https://user-images.githubusercontent.com/69638013/177015689-52b12f57-5b3a-4b59-843c-4206dc315a0a.png) |  ![Screenshot_307](https://user-images.githubusercontent.com/69638013/177015621-6d5309ee-cd06-4f12-a319-2f0a7dfaf8b2.png)

2022-07-02 21:10 UTC, prolajumokeoni commented on index.html
> +        </div>
- [ ] Kindly duplicate this card to be six just like in the Figma design, see screenshot above  👍🏿

2022-07-02 21:10 UTC, prolajumokeoni commented on index.html
> +    <div class="container-3">
- [ ] The container of the section is a section tag, please change the main wrapper of this section to a section tag, based on the requirements and for semantic purposes 👍🏿

2022-07-02 21:10 UTC, prolajumokeoni commented on index.html
> +            </div>
Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Template 2-Main-Mobile](https://user-images.githubusercontent.com/69638013/177016064-c237acdc-0abb-422c-91be-8bf03f83c85a.png) | ![Screenshot_308](https://user-images.githubusercontent.com/69638013/177016032-21ed39e3-ed18-45aa-b67f-33d4facadda6.png)

- [ ] Kindly align the background image to the right, please make your design look like the Figma
- [ ] Please align languages, frameworks and skills to the center

2022-07-04 19:21 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @Abrar052,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
>- [ ] From now on, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Wrong
![image](https://user-images.githubusercontent.com/52934128/177208022-e8945b23-548e-4642-92df-4836cac0ad73.png)
> ### Good Commit Messages:
>- [x]  Add fix for dark mode toggle state
>- [x] Update README file.
>- [x] Add styles to h1.
>
> 
> ## [Optional] suggestions:

>- [ ] kindly remove your `node_modules` folder from your `project-feature` GitHub branch as you may have mistakenly pushed  `node_modules` to your branch repo.
node_modules/ has a large size and is commonly excluded from the remote repository. :Smile:

> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-04 19:21 UTC, topeogunleye commented on index.html
> +    <div class="grid-container">
- [ ] As suggested by the previous code reviewer, I kindly suggest that you change this `div` tag to a `section` tag.

2022-07-04 19:21 UTC, topeogunleye commented on index.html
> +    <div class="container-3">
- [ ] As suggested by the previous code reviewer, I kindly suggest that you change this`div` tag to a`section` tag for [semantic](https://developer.mozilla.org/en-US/docs/Glossary/Semantics) purposes.

2022-07-04 19:21 UTC, topeogunleye commented on index.html
> +                    <h3 class="lan">Languages</h3>
- [ ] As suggested by the previous code reviewer, I kindly suggest that you add icons for language, framework, and skills.
![image](https://user-images.githubusercontent.com/52934128/177207349-378495bd-984c-4c3c-97d8-5bff951167cb.png)

2022-07-04 19:21 UTC, topeogunleye commented on index.html
> +                    <h3 class="fram"> Framworks</h3>
- [ ] As suggested by the previous code reviewer, I kindly suggest that you add icons for language, framework, and skills.
![image](https://user-images.githubusercontent.com/52934128/177207732-759da895-10e5-4de6-a3e3-8fa8480e07a9.png)

2022-07-04 19:21 UTC, topeogunleye commented on index.html
> +                    <h3 class="skills"> Skills</h3>
- [ ] As suggested by the previous code reviewer, I kindly suggest that you add icons for language, framework, and skills.
![image](https://user-images.githubusercontent.com/52934128/177207893-3fbb4160-a4ff-4235-8028-9a71bfe07f4d.png)

2022-07-04 19:26 UTC, Abrar052 commented on index.html
> +    <div class="grid-container">
@topeogunleye can you please tell me which div tag. The tag with class=container-2 or tag with grid-container.

2022-07-04 20:11 UTC, topeogunleye commented on index.html
> +    <div class="grid-container">
@Abrar052, Kindly use `<section class="grid-container"></section>` instead

2022-07-18 15:22 UTC, closed without merging